name: Trick-Or-Treat
version: '1.0'
main: me.lyamray.trickortreat.TOTMain
api-version: '1.21'
load: STARTUP
authors: [ LyamRay ]
description: A custom-made Trick Or Treat plugin, specially made for you!
depend: [Citizens]
commands:
  spawnnpc:
    descripton: Test command!
    aliases:
      - npc